### ISSUE TITLE
Build doesn't work

### ISSUE THREAD

**Issue by chpeter1174** [TheZeroSlave/WPE#1]
Hi. I was trying to build the sniffer but got some issues with it. I managed to build it with no error, but when trying to record packets I get error in Injector.cs with function DoWork() 
on line 133: realLength = Int32.Parse(strBuilder.ToString()); 
and 185: package.socketHandle = Int64.Parse(strBuilder.ToString()); 
It's giving me error "Input string was not in a correct format". Looking at debugger strBuilder value on line 185 was "A $", which doesn't look like socket number. When I change it to TryParse it goes through but the captured data is all mess. It shows mostly 0 and some data is in the From column. Do you have any idea what could cause this issue? Thanks
![Screenshot 2024-03-11 193101](https://github.com/TheZeroSlave/WPE/assets/86050716/71e37310-e19d-4adf-9082-b998265aca78)
![image](https://github.com/TheZeroSlave/WPE/assets/86050716/805c186d-0df5-45bc-920e-980590ce2b6b)

**Comment by chpeter1174** [comment]
Nvm, got it working

**Comment by yukismimi** [comment]
@chpeter1174 
Hello, I met the same issue and how can I fix it?
Thanks!

**Comment by yukismimi** [comment]
> @chpeter1174 Hello, I met the same issue and how can I fix it? Thanks!

got it working too.
