### ISSUE TITLE
I am having problems installing .NET Framework 4.0

### ISSUE THREAD

**Issue by somewere** [TheZeroSlave/WPE#3]
I am having problems installing .NET Framework 4.0

![image](https://github.com/user-attachments/assets/22f6c3f0-ebdb-4722-a1ea-5aff2319902e)

![Screenshot 2024-10-08 203911](https://github.com/user-attachments/assets/60c5104a-7399-4130-9091-d5cb04ab22f1)

![image](https://github.com/user-attachments/assets/41473034-322d-4b21-a49e-323595bdfd9a)

**Comment by TheZeroSlave** [comment]
pls pull update from main

**Comment by somewere** [comment]
> pls pull update from main

![Screenshot 2024-10-08 203911](https://github.com/user-attachments/assets/5e99c8ae-315a-43cc-8f18-b63c3a7ca8af)

can auto update  Socket id       send new   ?

**Comment by somewere** [comment]
> pls pull update from main

thank you
